[project]
name = "project_name"
version = "0.1.0"
description = "Description of the project."
readme = "README.md"
requires-python = ">=3.12.12,<3.13"
authors = [{ name = "Francesco Sodano" }]
license = { text = "MIT" }
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["black==26.1.0", "mypy==1.19.1", "pytest==9.0.2"]
